name = "Wold's Vaults"
author = "iwolfking"
version = "0.33.2hf"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfb243be79b55ed6e64be50e45f0a640176ef2c10501e76a0efed2b937b4edbe"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
