name = "Wold's Vaults"
author = "iwolfking"
version = "0.33.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "960616d9a9262cde796ae940af29e470dda6dafa33d64756495bc1768454cc76"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
