onEvent('jei.hide.items', event => {
    event.hide('the_vault:vault_jewel_cutting_station')
    event.hide('the_vault:vendor_door')
    event.hide('the_vault:dungeon_door')
    event.hide('the_vault:elite_controller_proxy')
    event.hide('the_vault:raid_controller_proxy')
    event.hide('the_vault:hologram')
    event.hide('the_vault:regret_orb')
    event.hide('the_vault:regret_shard')
    event.hide('the_vault:regret_nugget')
    event.hide('the_vault:god_blessing')
    event.hide('the_vault:charm_upgrade_tier_4')
    event.hide('the_vault:charm_upgrade_tier_3')
    event.hide('the_vault:charm_upgrade_tier_2')
    event.hide('the_vault:charm_upgrade_tier_1')
    event.hide('the_vault:vault_charm')
    event.hide('the_vault:aura_scroll')
    event.hide('the_vault:life_scroll')
    event.hide('the_vault:magnetite_ingot')
    event.hide('the_vault:magnetite')
    event.hide('the_vault:hunter_eye')
    event.hide('the_vault:unidentified_relic_fragment')
    event.hide('the_vault:skill_essence')
    event.hide('the_vault:poisonous_mushroom')
    event.hide('the_vault:skill_shard')
    event.hide('the_vault:legendary_treasure_omega')
    event.hide('the_vault:legendary_treasure_epic')
    event.hide('the_vault:legendary_treasure_rare')
    event.hide('the_vault:legendary_treasure_normal')
    event.hide('the_vault:relic_booster_pack')
    event.hide('the_vault:vault_relic_fragment')
    event.hide('the_vault:vault_relic')
    event.hide('the_vault:skill_orb')
    event.hide('the_vault:mote_sanctity')
    event.hide('the_vault:mote_purity')
    event.hide('the_vault:mote_clarity')
    event.hide('the_vault:paradoxical_gem')
    event.hide('woldsvaults:accoutre_focus')
    event.hide('pneumaticcraft:jet_boots_upgrade_1')
    event.hide('pneumaticcraft:jet_boots_upgrade_2')
    event.hide('pneumaticcraft:jet_boots_upgrade_3')
    event.hide('pneumaticcraft:jet_boots_upgrade_4')
    event.hide('pneumaticcraft:jet_boots_upgrade_5')
    event.hide('pneumaticcraft:jumping_upgrade_1')
    event.hide('pneumaticcraft:jumping_upgrade_2')
    event.hide('pneumaticcraft:jumping_upgrade_3')
    event.hide('pneumaticcraft:jumping_upgrade_4')
    event.hide('pneumaticcraft:elytra_upgrade')
    event.hide('pneumaticcraft:creative_upgrade')
    event.hide('industrialforegoing:infinity_hammer')
    event.hide('industrialforegoing:infinity_launcher')
    event.hide('industrialforegoing:infinity_nuke')
    event.hide('industrialforegoing:infinity_backpack')
    event.hide('industrialforegoing:mob_duplicator')
    event.hide('industrialforegoing:mob_imprisonment_tool')
    event.hide('ironchests:dirt_chest')
    event.hide('ironchests:obsidian_chest')
    event.hide('ironchests:crystal_chest')
    event.hide('ironchests:obsidian_chest_upgrade')
    event.hide('ironchests:crystal_chest_upgrade')
    event.hide('sophisticatedvaultupgrades:debagnetizer')
    event.hide(/mysticalagriculture:.*_helmet/)
    event.hide(/mysticalagriculture:.*_chestplate/)
    event.hide(/mysticalagriculture:.*_leggings/)
    event.hide(/mysticalagriculture:.*_boots/)
    event.hide(/mysticalagriculture:.*_sword/)
    event.hide(/mysticalagriculture:.*_pickaxe/)
    event.hide(/mysticalagriculture:.*_shovel/)
    event.hide(/mysticalagriculture:.*_axe/)
    event.hide(/mysticalagriculture:.*_bow/)
    event.hide(/mysticalagriculture:.*_crossbow/)
    event.hide(/mysticalagriculture:.*_augment/)
    event.hide(/ae2additions:.*component.*/)
    event.hide(/ae2additions:.*disk.*/)
    event.hide(/ae2additions:.*storage.*/)
    event.hide(/ae2additions:.*cell.*/)
    event.hide(/advancedperipherals:.*_core/)
    event.hide('advancedperipherals:chunk_controller')
    event.hide('angelring:itemring')
    event.hide('angelring:energetic_angel_ring')
    event.hide('angelring:leadstone_angel_ring')
    event.hide('angelring:hardened_angel_ring')
    event.hide('angelring:reinforced_angel_ring')
    event.hide('angelring:resonant_angel_ring')
    event.hide(/davespotioneering:.*_umbrella/)
    event.hide('woldsvaults:capstone_vendoors')
    event.hide('ars_nouveau:mundane_belt')
    event.hide('ars_nouveau:belt_of_unstable_gifts')
    event.hide('ars_nouveau:belt_of_levitation')
    event.hide('ars_nouveau:wixie_charm')
    event.hide('ars_nouveau:enchanters_shield')
    event.hide('draconiadditions:chaos_heart')
    event.hide('draconiadditions:chaos_container')
    event.hide('draconicevolution:stabilized_spawner')
    event.hide('draconicevolution:mob_soul')
    event.hide('draconicevolution:generator')
    event.hide('draconicevolution:mob_soul')
    event.hide('draconicevolution:creative_capacitor')
    event.hide('draconicevolution:info_tablet')
    event.hide('draconicevolution:creative_op_capacitor')
    event.hide('draconicevolution:draconium_chest')
    event.hide('draconicevolution:celestial_manipulator')
    event.hide('draconicevolution:dislocation_inhibitor')
    event.hide(/draconicadditions:.*_tick_accel/)
    event.hide(/draconicadditions:.*_harness/)
    event.hide(/draconicadditions:.*chaos_*/)
    event.hide(/draconicadditions:.*_necklace/)
    event.hide(/draconicevolution:.*dislocator/)
    event.hide(/draconicevolution:.*_sword/)
    event.hide(/draconicevolution:.*_staff/)
    event.hide(/draconicevolution:.*magnet/)
    event.hide(/draconicevolution:.*_pickaxe/)
    event.hide(/draconicadditions:.*_necklace/)
    event.hide(/draconicevolution:.*_chestpiece/)
    event.hide(/draconicevolution:.*_jump_module/)
    event.hide(/draconicevolution:.*_step_module/)
    event.hide(/draconicevolution:.*_feed_module/)
    event.hide(/draconicevolution:.*_undying_module/)
    event.hide(/draconicevolution:.*_flight_module/)
    event.hide(/draconicevolution:.*_recovery_module/)
    event.hide(/draconicevolution:.*_capacity_module/)
    event.hide(/draconicevolution:.*_control_module/)
    event.hide(/draconicevolution:.*_immune_module/)
    event.hide(/draconicevolution:.*_comp_module/)
    event.hide(/draconicevolution:.*_damage_module/)
    event.hide(/draconicevolution:.*_collection_module/)
    event.hide(/draconicevolution:.*_filter_module/)
    event.hide(/draconicevolution:.*_aoe_module/)
    event.hide(/draconicevolution:.*_speed_module/)


    //Blocks with rendering/crashing issues
    event.hide('blockcarpentry:frame_sign')
    event.hide('blockcarpentry:illusion_sign')
    event.hide(/ecologics:.*_sign/)
    event.hide(/quark:.*_sign/)
    event.hide(/tropicraft:.*_sign/)
    event.hide(/twigs:.*_sign/)
    event.hide(/dungeons_mobs:.*/)
    event.hide('sophisticatedbackpacks:copper_backpack')
    event.hide('sophisticatedbackpacks:stack_upgrade_starter_tier')
    event.hide('woldsvaults:augment_assembly_pedestal') //rip to a legend
})



onEvent('jei.add.items', event => {
    let modifierTypes = ["reaping", "picking", "axing", "shovelling", "ornate_affinity", "coin_affinity", "gilded_affinity", "living_affinity", "wooden_affinity", "hammering", "hydrovoid", "rotating", "durability", "immortality", "mining_speed", "item_quantity", "item_rarity", "trap_disarming", "soulbound", "smelting", "pulverizing"];
    event.add('the_vault:shop_pedestal')

    modifierTypes.forEach(type => {
        event.add(Item.of('woldsvaults:chiseling_focus', { modifier: `the_vault:${type}` }))
    })
    event.add(Item.of('woldsvaults:research_token', { research: "Waystones" }))

    //Stuff for Filters
    //Rarities
    event.add(Item.of('the_vault:chestplate', {
        "the_vault:gear_unique_pool": "the_vault:castle_chestplate", "the_vault:gear_roll_type": "Unique"
    }))
    event.add(Item.of('the_vault:chestplate', {
        "the_vault:gear_roll_type": "Omega"
    }))
})